# Site
name: "By Kyra"
title: "By Kyra"
description: "International introspections and personal projects, by Kyra."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
google_analytics: ''
disqus: 'kyrab2'
mailchimp-list: 'http://eepurl.com/hE1Aw5'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  kyra:
    name: Kyra
    display_name: Kyra    
    avatar: 'assets/images/logo.png'
    web: https://kyrab.github.io/
    description: "A data lover, lifelong learner, and traveler just trying to sort her thoughts (and life) out via blogging."
    instagram: https://www.instagram.com/theworldbykyra

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_trail: 2
paginate_show_first_and_last: true
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
